apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.elastest: "true"
  creationTimestamp: null
  labels:
    io.elastest.service.type: SUT
    io.elastest.service: full-teaching-openvidu-server-kms
  name: full-teaching-openvidu-server-kms
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.elastest: "true"
        io.elastest.service.type: SUT
        io.elastest.service: full-teaching-openvidu-server-kms
    spec:
      containers:
      - env:
        - name: KMS_STUN_IP
          value: stun.l.google.com
        - name: KMS_STUN_PORT
          value: "19302"
        - name: openvidu.publicurl
          value: docker
        - name: openvidu.secret
          value: MY_SECRET
        image: openvidu/openvidu-server-kms:1.7.0
        name: full-teaching-openvidu-server-kms
        ports:
        - containerPort: 8443
        resources: {}
      restartPolicy: Always
status: {}
