apiVersion: v1
kind: Service
metadata:
  annotations:
    io.elastest: "true"
  creationTimestamp: null
  labels:
    io.elastest: "true"
    io.elastest.service: full-teaching-openvidu-server-kms
    io.elastest.service.type: SUT
  name: full-teaching-openvidu-server-kms
spec:
  ports:
  - name: "full-teaching-openvidu-server-8443-node-port"
    port: 8443
    targetPort: 8443
    nodePort: 8443
  selector:
    io.elastest.service: full-teaching-openvidu-server-kms
  type: NodePort
status:
  loadBalancer: {}
