apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.elastest.service.type: SUT
  creationTimestamp: null
  labels:
    io.elastest: "true"
    io.elastest.service: full-teaching
  name: full-teaching
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.elastest: "true"
        io.elastest.service: full-teaching
    spec:
      containers:
      - env:
        - name: MYSQL_ENV_MYSQL_DATABASE
          value: full_teaching
        - name: MYSQL_ENV_MYSQL_PASSWORD
          value: pass
        - name: MYSQL_ENV_MYSQL_USER
          value: ft-root
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: full-teaching-mysql
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: WAIT_HOSTS
          value: full-teaching-mysql:3306
        - name: WAIT_HOSTS_TIMEOUT
          value: "120"
        - name: openvidu.secret
          value: MY_SECRET
        - name: openvidu.url
          value: https://full-teaching-openvidu-server-kms:8443
        - name: server.port
          value: "5000"
        image: codeurjc/full-teaching
        name: full-teaching
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
